Switch to Keycloak

diff --git a/services b/services
--- a/services
+++ b/services
@@ -4,14 +4,14 @@
 #
 #  For this tutorial the commands are merely a convenience script to run docker or docker-compose
 #
-#  Each services script can be run using either docker-compose (the external tool with the hyphen -) 
-#  or docker compose (the newer version directly bundled with Docker with a space )
+#  Each services script can be run using either docker-compose (the external tool with the hyphen -)
+#  or docker compose (the newer version directly bundled with Docker with a space)
 #
 #  if you start up with the following command:
 #
 #  ./services start legacy
 #
-# This will force the script to use docker-compose which may be more reliable in 
+# This will force the script to use docker-compose which may be more reliable in
 # some cases (or if an older version of Docker is being used)
 
 set -e
@@ -23,105 +23,86 @@ fi
 
 if (( $# < 1 )); then
     echo "Illegal number of parameters"
-    echo "usage: services [create|https|start|stop]"
+    echo "usage: services [create|start|stop]"
     exit 1
 fi
 
-
-startContainers () {
-	echo ""
-	export IDM_HTTPS_ENABLED="$1" 
-	${dockerCmd} up -d --remove-orphans
-	echo ""
-}
-
 displayServices () {
-	echo ""
-	docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" --filter name="$1"
-
-	echo ""
+    echo ""
+    docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" --filter name="$1"
+    echo ""
 }
 
 stoppingContainers () {
-	CONTAINERS=$(docker ps --filter "label=org.fiware=tutorial" -aq)
-	if [[ -n $CONTAINERS ]]; then 
-		echo "Stopping containers"
-		docker rm -f $CONTAINERS || true
-	fi
-	VOLUMES=$(docker volume ls -qf dangling=true) 
-	if [[ -n $VOLUMES ]]; then 
-		echo "Removing old volumes"
-		docker volume rm $VOLUMES || true
-	fi
-	NETWORKS=$(docker network ls  --filter "label=org.fiware=tutorial" -q) 
-	if [[ -n $NETWORKS ]]; then 
-		echo "Removing tutorial networks"
-		docker network rm $NETWORKS || true
-	fi
+    CONTAINERS=$(docker ps --filter "label=org.fiware=tutorial" -aq)
+    if [[ -n $CONTAINERS ]]; then
+        echo "Stopping containers"
+        docker rm -f $CONTAINERS || true
+    fi
+    VOLUMES=$(docker volume ls -qf dangling=true)
+    if [[ -n $VOLUMES ]]; then
+        echo "Removing old volumes"
+        docker volume rm $VOLUMES || true
+    fi
+    NETWORKS=$(docker network ls --filter "label=org.fiware=tutorial" -q)
+    if [[ -n $NETWORKS ]]; then
+        echo "Removing tutorial networks"
+        docker network rm $NETWORKS || true
+    fi
 }
 
-waitForKeyrock () {
-	echo -e "⏳ Waiting for \033[1;31mKeyrock\033[0m to be available\n"
-	
-	while [ `curl -s -o /dev/null -w %{http_code} 'http://localhost:3005/version'` -eq 000 ]
-	do 
-		echo -e "Keyrock HTTP state: " `curl -s -o /dev/null -w %{http_code} 'http://localhost:3005/version'` " (waiting for 200)"
-		sleep 5
-	done
-	echo -e " \033[1;32mdone\033[0m"
+waitForKeycloak () {
+    echo -e "\n⏳ Waiting for \033[1;34mKeycloak\033[0m to be available\n"
+    while ! [ "$(docker inspect --format='{{.State.Health.Status}}' fiware-keycloak 2>/dev/null)" == "healthy" ]
+    do
+        echo -e "Keycloak health: $(docker inspect --format='{{.State.Health.Status}}' fiware-keycloak 2>/dev/null) (waiting for healthy)"
+        sleep 5
+    done
+    echo -e " \033[1;32mdone\033[0m"
 }
 
-waitForSecureKeyrock () {
-	echo -e "⏳ Waiting for \033[1;31mKeyrock\033[0m to be available\n"
-	
-	while [ `curl -k -s -o /dev/null -w %{http_code} 'https://localhost:3443/version'` -eq 000 ]
-	do 
-		echo -e "Keyrock HTTP state: " `curl -k -s -o /dev/null -w %{http_code} 'https://localhost:3443/version'` " (waiting for 200)"
-		sleep 5
-	done
-	echo -e " \033[1;32mdone\033[0m"
+loadData () {
+    docker run --rm \
+        --network fiware_default \
+        -v "$(pwd)/import_users:/import_users" \
+        -e KEYCLOAK_HOST=keycloak \
+        -e KEYCLOAK_PORT=8080 \
+        --entrypoint /bin/ash \
+        "quay.io/curl/curl:${CURL_VERSION}" /import_users
 }
 
 command="$1"
 case "${command}" in
-	"help")
-        echo "usage: services [create|https|start|stop]"
+    "help")
+        echo "usage: services [create|start|stop]"
         ;;
-	"start")
-		export $(cat .env | grep "#" -v)
-		stoppingContainers
-		echo -e "Starting containers: \033[1;31mKeyrock\033[0m and a \033[1mMySQL\033[0m database."
-		echo -e "- \033[1;31mKeyrock\033[0m is an Identity Management Front-End under HTTP"
-		startContainers false
-		waitForKeyrock
-		displayServices
-		echo -e "Now open \033[4mhttp://localhost:3005/idm\033[0m"
-		;;
-	"https")
-		stoppingContainers
-		echo -e "Starting containers: \033[1;31mKeyrock\033[0m and a \033[1mMySQL\033[0m database."
-		echo -e "- \033[1;31mKeyrock\033[0m is an Identity Management Front-End under HTTPS"
-		startContainers true
-		waitForSecureKeyrock
-		displayServices
-		echo -e "Now open \033[4mhttps://localhost:3443/idm\033[0m"
-		;;
-	"stop")
-		export $(cat .env | grep "#" -v)
-		stoppingContainers
-		;;
-	"create")
-		export $(cat .env | grep "#" -v)
-		echo "Pulling Docker images"
-		docker pull -q quay.io/curl/curl:${CURL_VERSION}
-		${dockerCmd} pull --ignore-pull-failures
-		;;
-	*)
-		echo "Command not Found."
-		echo "usage: services [create|start|stop]"
-		exit 127;
-		;;
+    "start")
+        export $(cat .env | grep "#" -v)
+        stoppingContainers
+        echo -e "Starting containers: \033[1;34mKeycloak\033[0m and a \033[1mPostgreSQL\033[0m database."
+        echo -e "- \033[1;34mKeycloak\033[0m is the Identity and Access Management server"
+        echo -e "- \033[1mPostgreSQL\033[0m persists Keycloak realm, user, and session data"
+        echo ""
+        ${dockerCmd} up -d --remove-orphans
+        displayServices fiware
+        waitForKeycloak
+        loadData
+        echo -e "\033[1;34mKeycloak\033[0m is now running and exposed on localhost:${KEYCLOAK_PORT}"
+        echo -e "Now open \033[4mhttp://localhost:${KEYCLOAK_PORT}\033[0m"
+        ;;
+    "stop")
+        export $(cat .env | grep "#" -v)
+        stoppingContainers
+        ;;
+    "create")
+        export $(cat .env | grep "#" -v)
+        echo "Pulling Docker images"
+        docker pull -q "quay.io/curl/curl:${CURL_VERSION}"
+        ${dockerCmd} pull --ignore-pull-failures
+        ;;
+    *)
+        echo "Command not Found."
+        echo "usage: services [create|start|stop]"
+        exit 127;
+        ;;
 esac
-
-
-
